USE lfysdb;

-- Admins (30 rows)
INSERT INTO admins (user_id, level) VALUES
(1, 'super'), (2, 'super'), (3, 'super'),
(4, 'mod'), (5, 'mod'), (6, 'mod'), (7, 'mod'), (8, 'mod'),
(9, 'mod'), (10, 'mod'), (11, 'mod'), (12, 'mod'), (13, 'mod'),
(14, 'mod'), (15, 'mod'), (16, 'mod'), (17, 'mod'), (18, 'mod'),
(19, 'mod'), (20, 'mod'), (21, 'mod'), (22, 'mod'), (23, 'mod'),
(24, 'mod'), (25, 'mod'), (26, 'mod'), (27, 'mod'), (28, 'mod'),
(29, 'mod'), (30, 'mod');

-- Reports (40 rows)
INSERT INTO reports (user_id, content, type) VALUES
(31, 'Website bị lỗi khi tôi cố gắng nộp bài trong cuộc thi. Hiện thông báo "Internal Server Error 500" và không thể tiếp tục.', 'bug'),
(32, 'Tôi nghĩ nên thêm chức năng dark mode để dễ sử dụng hơn vào ban đêm. Màn hình sáng quá gây mỏi mắt.', 'feedback'),
(33, 'Người dùng với ID 45 đã sao chép solution từ internet trong cuộc thi. Tôi có bằng chứng screenshot.', 'violation'),
(34, 'Ứng dụng mobile crash liên tục khi tôi cố gắng xem leaderboard. Điện thoại Samsung Galaxy S23.', 'bug'),
(35, 'Đề xuất thêm phần thống kê chi tiết về tiến trình học tập, bao gồm biểu đồ và phân tích xu hướng.', 'feedback'),
(36, 'User @baduser liên tục spam tin nhắn quảng cáo trong các phòng chat. Rất phiền toái cho cộng đồng.', 'violation'),
(37, 'Khi submit code Python, hệ thống báo lỗi "Time Limit Exceeded" ngay cả với solution đơn giản nhất.', 'bug'),
(38, 'Nên có thêm ngôn ngữ lập trình Go và Rust trong danh sách lựa chọn. Nhiều người quan tâm.', 'feedback'),
(39, 'Phát hiện người dùng tạo nhiều tài khoản để vote cho bài viết của chính mình trong forum.', 'violation'),
(40, 'Page loading rất chậm, đặc biệt là phần problem list. Cần optimize performance.', 'bug');
/* (41, 'Đề xuất thêm tính năng collaborative coding để học viên có thể code chung trong real-time.', 'feedback'),
(42, 'Có user đăng nội dung không phù hợp trong course comment, bao gồm link đến website độc hại.', 'violation'),
(43, 'Badge system không cập nhật đúng. Tôi đã hoàn thành đủ điều kiện nhưng chưa nhận được badge.', 'bug'),
(44, 'Gợi ý thêm practice mode cho từng topic cụ thể, ví dụ chỉ luyện Dynamic Programming.', 'feedback'),
(45, 'Phát hiện giáo viên share key solution trong group chat riêng, vi phạm quy định contest.', 'violation'),
(46, 'Email notification không hoạt động. Tôi không nhận được thông báo khi có người reply comment.', 'bug'),
(47, 'Đề xuất tích hợp với GitHub để tự động sync code submissions vào personal repository.', 'feedback'),
(48, 'User harassment qua private message. Đã block nhưng vẫn tìm cách liên lạc qua account khác.', 'violation'),
(49, 'Contest timer hiển thị sai giờ, không đồng bộ với server time. Gây confusion cho participants.', 'bug'),
(50, 'Nên có video tutorials cho những người mới bắt đầu. Hiện tại chỉ có text khó hiểu.', 'feedback'),
(31, 'Phát hiện code plagiarism trong submissions. Nhiều bài giống hệt nhau từ different users.', 'violation'),
(32, 'Search function không hoạt động tốt với tiếng Việt. Cần cải thiện Vietnamese text processing.', 'bug'),
(33, 'Đề xuất thêm mobile app native thay vì chỉ có responsive web. Performance sẽ tốt hơn.', 'feedback'),
(34, 'Spam bot tạo hàng loạt fake account và đăng link quảng cáo trong forum posts.', 'violation'),
(35, 'Database connection timeout xảy ra thường xuyên vào giờ cao điểm. Cần scale infrastructure.', 'bug'),
(36, 'Gợi ý thêm gamification elements như daily challenges, streaks, và seasonal events.', 'feedback'),
(37, 'Phát hiện insider threat - admin abuse quyền hạn để xem private submissions của users.', 'violation'),
(38, 'Code editor thiếu syntax highlighting cho một số ngôn ngữ như Kotlin và Swift.', 'bug'),
(39, 'Đề xuất integration với coding interview platforms như LeetCode và HackerRank.', 'feedback'),
(40, 'User impersonation - có người giả mạo identity của popular instructor để scam students.', 'violation'),
(41, 'Memory leak trong code execution environment khiến server performance degraded.', 'bug'),
(42, 'Nên có AI-powered code review để đưa ra feedback tự động cho student submissions.', 'feedback'),
(43, 'Phát hiện data breach attempt - suspicious login patterns từ foreign IP addresses.', 'violation'),
(44, 'File upload feature không hoạt động với files lớn hơn 1MB. Cần tăng limit.', 'bug'),
(45, 'Đề xuất thêm peer review system để students có thể review code của nhau.', 'feedback'),
(46, 'Copyright violation - user upload tài liệu có bản quyền không được phép.', 'violation'),
(47, 'API rate limiting quá strict, block legitimate requests từ student applications.', 'bug'),
(48, 'Gợi ý thêm offline mode để có thể coding practice khi không có internet.', 'feedback'),
(49, 'Social engineering attack - scammer liên hệ students qua platform để lấy personal info.', 'violation'),
(50, 'Cross-site scripting vulnerability trong comment system. Cần patch security hole.', 'bug'); */

-- Notifications (45 rows)
INSERT INTO notifications (user_id, message, is_read) VALUES
(1, 'Chúc mừng! Bạn đã đạt level 10 và nhận được badge "Cao thủ". Tiếp tục cố gắng!', FALSE),
(2, 'Cuộc thi "Algorithm Marathon" sẽ bắt đầu trong 30 phút. Hãy chuẩn bị sẵn sàng!', FALSE),
(3, 'Có người mới comment trong bài viết "Dynamic Programming Tips" của bạn.', TRUE),
(4, 'Course "Advanced Data Structures" bạn đăng ký đã có bài học mới.', FALSE),
(5, 'Bạn có 1 tin nhắn mới từ instructor Nguyễn Văn A về assignment submission.', FALSE),
(6, 'Hệ thống sẽ maintenance từ 2:00-4:00 AM ngày mai. Vui lòng save work trước đó.', TRUE),
(7, 'Badge "Chăm chỉ" đã được thêm vào profile của bạn sau 7 ngày streak learning.', FALSE),
(8, 'Reminder: Contest "String Algorithms Battle" registration sẽ đóng trong 2 tiếng.', TRUE),
(9, 'Problem "Two Sum Variant" bạn đã solve được featured trong weekly newsletter.', FALSE),
(10, 'Bạn đã được invite tham gia private study group "Advanced Algorithms".', FALSE),
(11, 'Course rating của bạn cho "Python Fundamentals" đã được instructor phản hồi.', TRUE),
(12, 'Weekly leaderboard update: Bạn đang xếp hạng 15 với 2,450 XP.', FALSE),
(13, 'Có hint mới available cho problem "Graph Traversal" bạn đang struggle.', FALSE),
(14, 'Document "Algorithm Design Manual" bạn bookmark đã có update version.', TRUE),
(15, 'Congratulations! Bạn đã complete 50% course "Machine Learning Basics".', FALSE),
(16, 'Forum post "Best Practice for Code Review" của bạn đã đạt 100 upvotes.', FALSE),
(17, 'Referral bonus: +200 XP cho mỗi người bạn successfully invite join platform.', TRUE),
(18, 'Security alert: Phát hiện unusual login activity từ IP address mới.', FALSE),
(19, 'Quiz "Data Structure Fundamentals" results: Bạn đạt 85/100 điểm.', FALSE),
(20, 'New feature announcement: Dark mode đã available trong user settings.', TRUE),
(21, 'Contest "Binary Search Mastery" kết thúc. Bạn xếp hạng 8/45 participants.', FALSE),
(22, 'Instructor certification application của bạn đang được review bởi admin team.', FALSE),
(23, 'Monthly digest: Bạn đã solve 23 problems và complete 2 courses tháng này.', TRUE),
(24, 'Friend request từ Trần Thị B - cùng class Advanced Web Development.', FALSE),
(25, 'Code submission cho problem "Shortest Path" đã được accept với runtime 150ms.', FALSE),
(26, 'Seasonal event "Winter Programming Challenge" sẽ bắt đầu từ 15/12.', TRUE),
(27, 'AI code review cho submission gần nhất: "Good algorithm choice, optimize memory usage".', FALSE),
(28, 'Discussion thread "Career Advice for New Grads" có reply mới từ senior developer.', FALSE),
(29, 'Payment reminder: Premium subscription sẽ expire trong 7 ngày.', TRUE),
(30, 'Achievement unlocked: "Code Reviewer" - đã review 50 submissions của peers.', FALSE),
(31, 'Bug report bạn submit về contest timer đã được fix trong latest deployment.', FALSE),
(32, 'Feedback bạn đưa về dark mode đã được implement. Cảm ơn contribution!', TRUE),
(33, 'Report về code plagiarism đã được investigate. Appropriate action đã được taken.', FALSE),
(34, 'Mobile app crash issue đã được resolved trong version 2.1.3. Please update.', FALSE),
(35, 'Feature request về statistics dashboard đã được add vào development roadmap.', TRUE),
(36, 'User bạn report về spam đã bị permanent ban khỏi platform.', FALSE),
(37, 'Python execution timeout issue đã được fix với upgraded server infrastructure.', FALSE),
(38, 'Go và Rust programming languages đã được add vào supported languages list.', TRUE),
(39, 'Multi-account voting abuse case đã được resolved. Anti-fraud measures được strengthen.', FALSE),
(40, 'Performance optimization deployed. Problem list loading speed cải thiện 60%.', FALSE);
