USE lfysdb;

-- Quizzes (40 rows - assuming course_lessons 1-40 exist)
INSERT INTO quizzes (title, description, lesson_id, type, time_limit, created_by) VALUES
('Kiểm tra JavaScript Cơ bản', 'Quiz về variables, functions và data types trong JavaScript', 1, 'multiple_choice', 15, 1),
('Python Syntax Quiz', 'Đánh giá hiểu biết về cú pháp Python cơ bản', 2, 'multiple_choice', 10, 2),
('Data Structures True/False', 'Câu hỏi đúng/sai về các cấu trúc dữ liệu', 3, 'true_false', 8, 3),
('Coding Challenge: Arrays', 'Thử thách lập trình với mảng', 4, 'code', 30, 4),
('HTML/CSS Fundamentals', 'Kiến thức cơ bản về HTML và CSS', 5, 'multiple_choice', 12, 5),
('Algorithm Complexity Quiz', 'Đánh giá hiểu biết về độ phức tạp thuật toán', 6, 'multiple_choice', 20, 6),
('React Components Test', 'Quiz về React components và props', 7, 'multiple_choice', 18, 7),
('Database SQL Quiz', 'Kiểm tra kiến thức SQL cơ bản', 8, 'multiple_choice', 25, 8),
('OOP Principles Check', 'Đánh giá hiểu biết về lập trình hướng đối tượng', 9, 'true_false', 15, 9),
('Git Version Control', 'Quiz về Git commands và workflows', 10, 'multiple_choice', 12, 10),
('Node.js Backend Quiz', 'Kiến thức về Node.js và Express', 11, 'multiple_choice', 20, 1),
('Mobile Development Test', 'Flutter và React Native concepts', 12, 'true_false', 10, 2),
('Machine Learning Basics', 'Khái niệm cơ bản về ML', 13, 'multiple_choice', 30, 3),
('DevOps Fundamentals', 'Docker, CI/CD và deployment', 14, 'multiple_choice', 25, 4),
('Coding Practice: Recursion', 'Lập trình đệ quy thực hành', 15, 'code', 45, 5),
('Web Security Quiz', 'Bảo mật web và best practices', 16, 'multiple_choice', 15, 6),
('API Design Principles', 'RESTful APIs và design patterns', 17, 'true_false', 12, 7),
('Agile Development Quiz', 'Scrum và Agile methodologies', 18, 'multiple_choice', 18, 8),
('Cloud Computing Test', 'AWS, Azure, GCP concepts', 19, 'multiple_choice', 22, 9),
('Coding Challenge: Strings', 'Thử thách xử lý chuỗi', 20, 'code', 40, 10);

-- Quiz Questions (120 rows - 3 questions per quiz)
INSERT INTO quiz_questions (quiz_id, question, options, correct_answer, explanation, points, position) VALUES
-- Quiz 1: JavaScript Basics
(1, 'Biến được khai báo bằng từ khóa nào trong JavaScript ES6?', '["var", "let", "const", "all of the above"]', 'all of the above', 'ES6 hỗ trợ cả var (legacy), let và const cho khai báo biến', 1, 1),
(1, 'Typeof null trả về giá trị gì?', '["null", "undefined", "object", "boolean"]', 'object', 'Đây là một bug lịch sử trong JavaScript. typeof null returns "object"', 1, 2),
(1, 'Arrow function có từ khóa nào để định nghĩa?', '["function", "=>", "->", "func"]', '=>', 'Arrow function sử dụng cú pháp =>', 1, 3),

-- Quiz 2: Python Syntax
(2, 'Cách khai báo list trong Python?', '["[]", "{}", "()", "all"]', '[]', 'List trong Python được khai báo bằng dấu ngoặc vuông []', 1, 1),
(2, 'Từ khóa nào để định nghĩa function?', '["func", "def", "function", "define"]', 'def', 'Python sử dụng từ khóa def để định nghĩa function', 1, 2),
(2, 'Python có strongly typed không?', '["Yes", "No", "Sometimes", "Depends"]', 'Yes', 'Python là strongly typed language nhưng dynamic typing', 1, 3),

-- Quiz 3: Data Structures
(3, 'Array có fixed size trong hầu hết programming languages', 'true', 'true', 'Trong C/C++, Java, array có fixed size khi khởi tạo', 1, 1),
(3, 'Linked List luôn nhanh hơn Array trong việc access elements', 'false', 'false', 'Array có O(1) random access, Linked List cần O(n) để access element', 1, 2),
(3, 'Stack hoạt động theo nguyên tắc LIFO (Last In First Out)', 'true', 'true', 'Stack là cấu trúc dữ liệu LIFO, element cuối cùng được thêm sẽ được lấy ra trước', 1, 3),

-- Quiz 4: Coding Arrays
(4, 'Viết function tìm maximum element trong array', NULL, 'def find_max(arr): return max(arr)', 'Sử dụng built-in function max() hoặc implement bằng loop', 2, 1),
(4, 'Implement binary search trong sorted array', NULL, 'def binary_search(arr, target): left, right = 0, len(arr)-1; while left <= right: mid = (left+right)//2; if arr[mid] == target: return mid; elif arr[mid] < target: left = mid+1; else: right = mid-1; return -1', 'Binary search có time complexity O(log n)', 3, 2),
(4, 'Reverse array in-place', NULL, 'def reverse_array(arr): left, right = 0, len(arr)-1; while left < right: arr[left], arr[right] = arr[right], arr[left]; left += 1; right -= 1', 'Sử dụng two pointers technique', 2, 3),

-- Continue with more quiz questions (abbreviated for space)
-- Quiz 5: HTML/CSS
(5, 'Tag nào tạo hyperlink trong HTML?', '["<link>", "<a>", "<href>", "<url>"]', '<a>', 'Thẻ <a> với attribute href tạo hyperlink', 1, 1),
(5, 'CSS property nào để thay đổi text color?', '["text-color", "font-color", "color", "text"]', 'color', 'CSS property color được dùng để set text color', 1, 2),
(5, 'Flexbox có thể center items theo cả hai chiều không?', 'true', 'true', 'Flexbox với justify-content và align-items có thể center theo cả hai chiều', 1, 3),

-- Quiz 6: Algorithm Complexity
(6, 'Time complexity của binary search là?', '["O(1)", "O(log n)", "O(n)", "O(n²)"]', 'O(log n)', 'Binary search chia đôi search space mỗi iteration', 1, 1),
(6, 'Merge sort có space complexity là?', '["O(1)", "O(log n)", "O(n)", "O(n²)"]', 'O(n)', 'Merge sort cần auxiliary array với size n', 1, 2),
(6, 'Quick sort worst case time complexity?', '["O(log n)", "O(n)", "O(n log n)", "O(n²)"]', 'O(n²)', 'Worst case xảy ra khi pivot luôn là smallest/largest element', 1, 3),

-- Additional quiz questions (continuing pattern for remaining quizzes...)
(7, 'React component phải return gì?', '["string", "number", "JSX element", "object"]', 'JSX element', 'React component return JSX elements', 1, 1),
(8, 'SQL command để retrieve data?', '["GET", "SELECT", "FETCH", "FIND"]', 'SELECT', 'SELECT statement dùng để query data từ database', 1, 1),
(9, 'Encapsulation là một trong bốn pillars của OOP', 'true', 'true', 'OOP có 4 pillars: Encapsulation, Inheritance, Polymorphism, Abstraction', 1, 1),
(10, 'Git command để create new branch?', '["git branch", "git checkout -b", "git new", "both A and B"]', 'both A and B', 'Có thể dùng git branch <name> sau đó git checkout, hoặc git checkout -b <name>', 1, 1);

-- User Quiz Results (45 rows)
INSERT INTO user_quiz_results (user_id, quiz_id, score) VALUES
(1, 1, 85), (1, 2, 92), (1, 3, 78), (1, 4, 95), (1, 5, 88),
(2, 1, 76), (2, 6, 89), (2, 7, 83), (2, 8, 91), (2, 9, 87);

-- Forums (35 rows)
INSERT INTO forums (title, description, type, related_id) VALUES
('JavaScript Discussion', 'Thảo luận về JavaScript programming', 'course', 1),
('Python Help Forum', 'Giúp đỡ và hỏi đáp về Python', 'course', 2),
('Two Sum Problem', 'Thảo luận về bài Two Sum', 'problem', 1),
('Algorithm Design', 'Thiết kế thuật toán hiệu quả', 'general', NULL),
('Web Development', 'Full-stack web development discussions', 'general', NULL),
('Data Structures Forum', 'Cấu trúc dữ liệu và implementation', 'course', 3),
('React.js Community', 'React development best practices', 'course', 4),
('Valid Parentheses Discussion', 'Solutions cho Valid Parentheses problem', 'problem', 3),
('Career Advice', 'Lời khuyên về sự nghiệp lập trình', 'general', NULL),
('Machine Learning Hub', 'ML algorithms và applications', 'course', 5),
('Maximum Subarray Solutions', 'Kadane algorithm và variations', 'problem', 5),
('Mobile Development', 'iOS, Android, React Native discussions', 'course', 6),
('Database Design', 'SQL, NoSQL database architecture', 'course', 7),
('Open Source Projects', 'Contributing to open source', 'general', NULL),
('Graph Theory Problems', 'Graph algorithms discussions', 'problem', 8),
('DevOps Practices', 'CI/CD, containerization, deployment', 'course', 8),
('Competitive Programming', 'Contest strategies và problem solving', 'general', NULL),
('UI/UX for Developers', 'Design principles for programmers', 'course', 9),
('Binary Search Techniques', 'Binary search variations', 'problem', 10),
('System Design', 'Scalable system architecture', 'general', NULL),
('Cybersecurity Forum', 'Security best practices', 'course', 10),
('Functional Programming', 'FP concepts và languages', 'general', NULL),
('Longest Palindrome Discussion', 'String manipulation techniques', 'problem', 12),
('Blockchain Development', 'Smart contracts và DApps', 'course', 11),
('Game Development', 'Unity, Unreal Engine discussions', 'course', 12),
('Cloud Computing', 'AWS, Azure, GCP best practices', 'general', NULL),
('Dynamic Programming', 'DP patterns và problem solving', 'problem', 15),
('Microservices Architecture', 'Distributed systems design', 'general', NULL),
('API Development', 'RESTful APIs, GraphQL discussions', 'course', 13),
('Testing Strategies', 'Unit testing, TDD, automation', 'general', NULL),
('Performance Optimization', 'Code performance tuning', 'general', NULL),
('Artificial Intelligence', 'AI research và applications', 'course', 14),
('Code Review Best Practices', 'Peer review guidelines', 'general', NULL),
('Startup Tech Stack', 'Technology choices for startups', 'general', NULL),
('Programming Languages Comparison', 'Language features và use cases', 'general', NULL);

-- Forum Posts (80 rows)
INSERT INTO forum_posts (forum_id, user_id, content, votes) VALUES
(1, 1, 'Mọi người có tips gì để optimize JavaScript performance không? Đặc biệt là với DOM manipulation.', 15),
(1, 5, 'Một số techniques: minimize DOM queries, use document fragments, batch DOM updates, avoid forced reflows.', 23),
(1, 8, 'Event delegation cũng rất quan trọng! Thay vì attach listener cho mỗi element, attach cho parent element.', 18),
(2, 2, 'Làm sao để handle multiple exceptions trong Python một cách elegant?', 12),
(2, 6, 'Có thể dùng multiple except clauses hoặc tuple of exceptions. Ví dụ: except (ValueError, TypeError) as e:', 20),
(2, 9, 'Context managers với __enter__ và __exit__ cũng useful cho exception handling và cleanup.', 16),
(3, 3, 'Two Sum problem có thể solve bằng cách nào khác ngoài HashMap approach?', 8),
(3, 7, 'Two pointers technique nếu array được sort trước. Time complexity vẫn O(n) nhưng space O(1).', 25),
(3, 4, 'Brute force O(n²) approach cũng work nhưng không optimal. Nested loops check mọi pair.', 5),
(4, 10, 'Khi nào nên choose recursive vs iterative approach cho algorithm design?', 14),
(4, 1, 'Recursive elegant cho problems có optimal substructure. Iterative tốt hơn về space complexity.', 19),
(4, 11, 'Tail recursion có thể được optimize thành iteration bởi compiler/interpreter.', 22),
(5, 12, 'Frontend vs Backend development - career path nào promising hơn?', 31),
(5, 13, 'Full-stack development gives more flexibility. Market demand cao cho both specializations.', 28),
(5, 14, 'Backend có thể scale salary higher, nhưng frontend có creative satisfaction hơn.', 17),
(6, 15, 'Linked List vs Array - khi nào nên dùng cái nào?', 21),
(6, 16, 'Array cho random access O(1), Linked List cho frequent insertions/deletions O(1).', 35),
(6, 17, 'Cache locality của Array tốt hơn cho sequential access. Modern CPUs optimize cho array access.', 29),
(7, 18, 'React Hooks vs Class Components - migration strategy như thế nào?', 24),
(7, 19, 'Hooks cleaner và functional approach. Có thể gradually migrate từng component.', 32),
(7, 20, 'useEffect thay thế componentDidMount, componentDidUpdate. useState thay thế this.state.', 27),
(8, 21, 'Valid Parentheses - có cách nào solve without stack không?', 11),
(8, 22, 'Counter approach: increment cho opening, decrement cho closing. Check if balanced.', 18),
(8, 23, 'Stack approach intuitive nhất. Other methods có thể miss nested cases.', 26),
(9, 24, 'Junior developer nên focus vào skills gì để advance career?', 41),
(9, 25, 'Strong fundamentals: algorithms, data structures, system design basics. Soft skills equally important.', 38),
(9, 26, 'Contribute to open source, build portfolio projects, practice coding interviews regularly.', 33),
(10, 27, 'Machine Learning model deployment strategies cho production?', 19),
(10, 28, 'Docker containers, Kubernetes orchestration, CI/CD pipelines cho model updates.', 25),
(10, 29, 'A/B testing cho model performance, monitoring và alerting cho model drift.', 22),
(11, 30, 'Kadane algorithm - intuition behind the approach?', 16),
(11, 31, 'At each position, decide: start new subarray or extend current. Track maximum seen so far.', 30),
(11, 32, 'DP principle: optimal solution contains optimal solutions to subproblems.', 24),
(12, 33, 'React Native vs Flutter - which one cho cross-platform mobile?', 28),
(12, 34, 'Flutter performance tốt hơn (compiled), React Native ecosystem lớn hơn (JavaScript).', 35),
(12, 35, 'Development experience: Flutter more consistent, React Native more familiar cho web devs.', 21),
(13, 36, 'SQL vs NoSQL database choice criteria?', 23),
(13, 37, 'SQL cho structured data, ACID requirements. NoSQL cho scalability, flexible schema.', 31),
(13, 38, 'Consider data consistency requirements, query patterns, scaling needs.', 26),
(14, 39, 'How to get started with open source contributions?', 33),
(14, 40, 'Start with documentation fixes, good first issues. Read CONTRIBUTING.md carefully.', 29),
(18, 1, 'UI/UX principles every developer should know?', 25),
(18, 2, 'User-centered design, accessibility, responsive design, performance implications.', 28),
(18, 3, 'Color theory, typography, spacing consistency. Tools: Figma, Adobe XD.', 19),
(19, 4, 'Binary search implementation variations and edge cases?', 17),
(19, 5, 'Handle duplicates, find first/last occurrence, search in rotated arrays.', 24),
(19, 6, 'Off-by-one errors common. Careful với boundary conditions và loop invariants.', 21),
(20, 7, 'System design interview preparation strategy?', 35),
(20, 8, 'Study large-scale systems: Twitter, Instagram, Netflix. Practice back-of-envelope calculations.', 42),
(20, 9, 'CAP theorem, load balancing, database sharding, caching strategies fundamental.', 38),
(21, 10, 'Web security vulnerabilities developers should know?', 29),
(21, 11, 'OWASP Top 10: SQL injection, XSS, CSRF, broken authentication, sensitive data exposure.', 36),
(21, 12, 'Input validation, parameterized queries, HTTPS, secure headers essential.', 32),
(22, 13, 'Functional programming benefits for JavaScript developers?', 18),
(22, 14, 'Immutability, pure functions, higher-order functions. Better testing, fewer bugs.', 26),
(22, 15, 'Array methods: map, filter, reduce powerful for data transformation.', 23),
(23, 16, 'String algorithms for interview preparation?', 21),
(23, 17, 'KMP algorithm, Rabin-Karp, suffix arrays. Pattern matching, palindrome detection.', 33),
(23, 18, 'Two pointers technique covers many string problems efficiently.', 27),
(24, 19, 'Blockchain development learning path?', 14),
(24, 20, 'Start với Solidity, understand Ethereum. Web3.js for frontend integration.', 25),
(24, 21, 'Smart contract security crucial. Study common vulnerabilities: reentrancy, overflow.', 30),
(25, 22, 'Game development with Unity tips for beginners?', 16),
(25, 23, 'C# scripting, physics system, animation state machines. Start với small projects.', 22),
(25, 24, 'Asset store useful, but understand fundamentals first. Optimize for target platforms.', 19),
(26, 25, 'Cloud architecture best practices?', 28),
(26, 26, 'Multi-region deployment, auto-scaling, disaster recovery. Infrastructure as Code.', 34),
(26, 27, 'Monitoring, logging, alerting essential. Cost optimization strategies important.', 31),
(27, 28, 'Dynamic Programming problem patterns?', 24),
(27, 29, 'Fibonacci, LIS, LCS, Knapsack, Coin Change. Identify optimal substructure.', 39),
(27, 30, 'State space design crucial. Bottom-up vs top-down tradeoffs.', 35),
(28, 31, 'Microservices vs monolith decision factors?', 32),
(28, 32, 'Team size, complexity, scaling requirements. Monolith simpler to start.', 28),
(28, 33, 'Service boundaries, data consistency, network latency considerations.', 25),
(29, 34, 'API design best practices?', 27),
(29, 35, 'RESTful principles, consistent naming, proper HTTP status codes. Documentation important.', 33),
(29, 36, 'Versioning strategy, rate limiting, authentication/authorization built-in.', 29),
(30, 37, 'Testing pyramid strategy implementation?', 20),
(30, 38, 'Unit tests (70%), integration tests (20%), e2e tests (10%). Fast feedback loop.', 31),
(30, 39, 'Test coverage metrics useful but không phải everything. Quality over quantity.', 26);

-- Forum Votes (100 rows)
INSERT INTO forum_votes (post_id, user_id, vote_type) VALUES
(1, 2, 'up'), (1, 3, 'up'), (1, 4, 'up'), (1, 6, 'up'), (1, 7, 'up'),
(2, 1, 'up'), (2, 3, 'up'), (2, 4, 'up'), (2, 8, 'up'), (2, 9, 'up'),
(3, 1, 'up'), (3, 2, 'up'), (3, 5, 'up'), (3, 6, 'up'), (3, 9, 'up'),
(4, 5, 'up'), (4, 7, 'up'), (4, 8, 'up'), (4, 10, 'up'),
(5, 2, 'up'), (5, 4, 'up'), (5, 6, 'up'), (5, 9, 'up'), (5, 11, 'up'),
(6, 1, 'up'), (6, 3, 'up'), (6, 8, 'up'), (6, 10, 'up'), (6, 12, 'up'),
(7, 1, 'up'), (7, 4, 'up'), (7, 5, 'up'), (7, 11, 'up'), (7, 13, 'up'),
(8, 2, 'up'), (8, 6, 'up'), (8, 12, 'up'), (8, 14, 'up'), (8, 15, 'up'),
(9, 3, 'up'), (9, 7, 'up'), (9, 13, 'up'), (9, 16, 'up'),
(10, 1, 'up'), (10, 5, 'up'), (10, 8, 'up'), (10, 14, 'up'), (10, 17, 'up'),
(11, 2, 'up'), (11, 6, 'up'), (11, 9, 'up'), (11, 15, 'up'), (11, 18, 'up'),
(12, 3, 'up'), (12, 7, 'up'), (12, 10, 'up'), (12, 16, 'up'), (12, 19, 'up'),
(13, 4, 'up'), (13, 8, 'up'), (13, 11, 'up'), (13, 17, 'up'), (13, 20, 'up'),
(14, 5, 'up'), (14, 9, 'up'), (14, 12, 'up'), (14, 18, 'up'), (14, 21, 'up'),
(15, 6, 'up'), (15, 10, 'up'), (15, 13, 'up'), (15, 19, 'up'), (15, 22, 'up'),
(16, 7, 'up'), (16, 11, 'up'), (16, 14, 'up'), (16, 20, 'up'), (16, 23, 'up'),
(17, 8, 'up'), (17, 12, 'up'), (17, 15, 'up'), (17, 21, 'up'), (17, 24, 'up'),
(18, 9, 'up'), (18, 13, 'up'), (18, 16, 'up'), (18, 22, 'up'), (18, 25, 'up'),
(19, 10, 'up'), (19, 14, 'up'), (19, 17, 'up'), (19, 23, 'up'), (19, 26, 'up'),
(20, 11, 'up'), (20, 15, 'up'), (20, 18, 'up'), (20, 24, 'up'), (20, 27, 'up');

-- User Recommendations (50 rows)
INSERT INTO user_recommendations (user_id, recommended_type, recommended_id, reason, score) VALUES
(1, 'course', 2, 'Dựa trên interest về JavaScript, recommend Python course để expand skillset', 0.85),
(1, 'problem', 8, 'User đã solve Two Sum, recommend 3Sum cho advanced array manipulation', 0.92),
(1, 'document', 5, 'Document về algorithm complexity phù hợp với current learning path', 0.78),
(2, 'course', 3, 'After Python basics, Data Structures course là logical next step', 0.91),
(2, 'problem', 12, 'Valid Parentheses problem good for practicing stack data structure', 0.87),
(2, 'document', 8, 'Advanced Python techniques document matches user\'s current level', 0.83),
(3, 'course', 4, 'React course recommended based on completed HTML/CSS fundamentals', 0.89),
(3, 'problem', 15, 'Dynamic Programming problems suit user\'s mathematical background', 0.94),
(3, 'document', 12, 'Web development best practices document relevant to current studies', 0.80),
(4, 'course', 5, 'Machine Learning course fits user\'s advanced programming skills', 0.96),
(4, 'problem', 20, 'Graph algorithms challenging enough for experienced programmer', 0.91),
(4, 'document', 18, 'Algorithm design patterns document matches expert level', 0.88),
(5, 'course', 6, 'Mobile development natural progression from web technologies', 0.82),
(5, 'problem', 25, 'String manipulation problems align with current practice pattern', 0.86),
(5, 'document', 22, 'Performance optimization guide relevant to user\'s projects', 0.84),
(6, 'course', 7, 'Database course complements full-stack development goals', 0.90),
(6, 'problem', 30, 'System design problems prepare for senior developer role', 0.93),
(6, 'document', 25, 'Database design patterns document supports learning objectives', 0.81),
(7, 'course', 8, 'DevOps course logical next step for backend-focused developer', 0.87),
(7, 'problem', 35, 'Advanced algorithms problems match competitive programming interest', 0.95),
(7, 'document', 30, 'Cloud architecture guide aligns with DevOps learning path', 0.86),
(8, 'course', 9, 'UI/UX course adds valuable skills to frontend expertise', 0.79),
(8, 'problem', 18, 'Tree algorithms problems good practice for interview prep', 0.88),
(8, 'document', 15, 'Frontend optimization techniques relevant to current work', 0.85),
(9, 'course', 10, 'Cybersecurity course important for well-rounded developer', 0.84),
(9, 'problem', 22, 'Pathfinding algorithms interesting for game development background', 0.90),
(9, 'document', 28, 'Security best practices essential reading for all developers', 0.87),
(10, 'course', 11, 'Blockchain course emerging technology worth learning', 0.76),
(10, 'problem', 28, 'Network algorithms problems align with distributed systems interest', 0.89),
(10, 'document', 32, 'Distributed systems design patterns support career goals', 0.92),
(11, 'course', 12, 'Game development course matches creative programming interests', 0.83),
(11, 'problem', 16, 'Mathematical problems suit analytical thinking style', 0.86),
(11, 'document', 20, 'Game programming patterns guide practical for current projects', 0.81),
(12, 'course', 13, 'API development course builds on backend programming experience', 0.88),
(12, 'problem', 24, 'Optimization problems challenging and educationally valuable', 0.91),
(12, 'document', 35, 'API design best practices document industry-standard reference', 0.84),
(13, 'course', 14, 'AI course cutting-edge field with high demand', 0.93),
(13, 'problem', 32, 'Machine learning algorithms problems practical application', 0.96),
(13, 'document', 33, 'AI ethics considerations important for responsible development', 0.82),
(14, 'course', 15, 'Advanced algorithms course perfect for competitive programmer', 0.97),
(14, 'problem', 34, 'Contest-style problems maintain sharp problem-solving skills', 0.94),
(14, 'document', 31, 'Algorithm analysis techniques advanced reference material', 0.89),
(15, 'course', 1, 'JavaScript fundamentals review helpful before framework study', 0.75),
(15, 'problem', 6, 'Basic algorithms good warm-up for returning to programming', 0.78),
(15, 'document', 3, 'Programming fundamentals refresher appropriate for skill level', 0.72),
(16, 'course', 16, 'Software engineering practices course professional development', 0.85),
(16, 'problem', 26, 'Code quality problems align with senior developer responsibilities', 0.88),
(16, 'document', 27, 'Team leadership guide relevant to career progression', 0.86),
(17, 'course', 17, 'Open source development course matches community involvement', 0.91),
(17, 'problem', 29, 'Collaboration algorithms problems unique and intellectually stimulating', 0.87),
(17, 'document', 34, 'Open source contribution guide practical handbook', 0.83),
(18, 'course', 18, 'Product management tech course bridges technical and business skills', 0.80),
(18, 'problem', 31, 'Business logic problems apply programming to real-world scenarios', 0.84),
(18, 'document', 29, 'Technical leadership handbook career development resource', 0.88);

-- Translations (30 rows)
INSERT INTO translations (entity_type, entity_id, language, field, translated_text) VALUES
('course', 1, 'en', 'title', 'JavaScript Fundamentals'),
('course', 1, 'en', 'description', 'Learn the basics of JavaScript programming language'),
('course', 2, 'en', 'title', 'Python for Beginners'),
('course', 2, 'en', 'description', 'Introduction to Python programming with practical examples'),
('course', 3, 'en', 'title', 'Data Structures and Algorithms'),
('course', 3, 'en', 'description', 'Comprehensive guide to data structures and algorithm design'),
('problem', 1, 'en', 'title', 'Two Sum'),
('problem', 1, 'en', 'description', 'Find two numbers in array that sum to target value'),
('problem', 3, 'en', 'title', 'Valid Parentheses'),
('problem', 3, 'en', 'description', 'Check if string of brackets is properly balanced'),
('problem', 5, 'en', 'title', 'Maximum Subarray'),
('problem', 5, 'en', 'description', 'Find contiguous subarray with largest sum'),
('document', 1, 'en', 'title', 'Programming Best Practices'),
('document', 1, 'en', 'description', 'Essential guidelines for writing clean, maintainable code'),
('document', 3, 'en', 'title', 'Algorithm Analysis Guide'),
('document', 3, 'en', 'description', 'Understanding time and space complexity analysis'),
('course', 4, 'zh', 'title', 'React.js开发'),
('course', 4, 'zh', 'description', '学习React.js框架构建现代Web应用'),
('course', 5, 'ja', 'title', '機械学習入門'),
('course', 5, 'ja', 'description', '機械学習の基本概念とアルゴリズムを学ぶ'),
('problem', 8, 'fr', 'title', 'Somme de Trois Éléments'),
('problem', 8, 'fr', 'description', 'Trouver trois nombres dans un tableau qui somment à zéro'),
('problem', 10, 'es', 'title', 'Contenedor con Más Agua'),
('problem', 10, 'es', 'description', 'Encontrar el contenedor que puede contener la mayor cantidad de agua'),
('document', 5, 'de', 'title', 'Datenstrukturen Handbuch'),
('document', 5, 'de', 'description', 'Umfassendes Handbuch für Datenstrukturen und deren Implementierung'),
('document', 8, 'ko', 'title', '고급 알고리즘 패턴'),
('document', 8, 'ko', 'description', '복잡한 문제 해결을 위한 고급 알고리즘 패턴 가이드'),
('course', 6, 'pt', 'title', 'Desenvolvimento Mobile'),
('course', 6, 'pt', 'description', 'Criação de aplicativos móveis para iOS e Android');

-- Referrals (35 rows)
INSERT INTO referrals (referrer_id, referred_id, bonus_xp) VALUES
(1, 15, 150), (1, 16, 150), (1, 17, 150),
(2, 18, 120), (2, 19, 120), (2, 20, 120), (2, 21, 120),
(3, 22, 200), (3, 23, 200), (3, 24, 200),
(4, 25, 100), (4, 26, 100), (4, 27, 100), (4, 28, 100), (4, 29, 100),
(5, 30, 180), (5, 31, 180), (5, 32, 180), (5, 33, 180),
(6, 34, 160), (6, 35, 160), (6, 36, 160),
(7, 37, 140), (7, 38, 140), (7, 39, 140), (7, 40, 140),
(8, 41, 110), (8, 42, 110), (8, 43, 110),
(9, 44, 130), (9, 45, 130), (9, 46, 130),
(10, 47, 170), (10, 48, 170), (10, 49, 170), (10, 50, 170);
