USE lfysdb;

-- Insert data vào bảng topics (20 chủ đề)
INSERT INTO topics (name) VALUES
('Thuật toán và Cấu trúc dữ liệu'),
('Lập trình hướng đối tượng'),
('Cơ sở dữ liệu'),
('Phát triển Web Frontend'),
('Phát triển Web Backend'),
('Phát triển Mobile'),
('Machine Learning'),
('Bảo mật thông tin'),
('DevOps và Cloud Computing'),
('Game Development'),
('Blockchain và Cryptocurrency'),
('Data Science và Analytics'),
('UI/UX Design'),
('System Design'),
('Software Testing'),
('Internet of Things (IoT)'),
('Artificial Intelligence'),
('Network Programming'),
('Operating Systems'),
('Software Engineering');

-- Insert data vào bảng document_categories (12 danh mục tài liệu)
INSERT INTO document_categories (name, description) VALUES
('Tutorial cơ bản', 'Các tài liệu hướng dẫn cơ bản cho người mới bắt đầu'),
('Advanced Guides', 'Hướng dẫn nâng cao cho developers có kinh nghiệm'),
('Code Examples', 'Các ví dụ code thực tế và best practices'),
('Reference Documentation', 'Tài liệu tham khảo API và thư viện'),
('Project Walkthroughs', 'Hướng dẫn xây dựng dự án từ đầu đến cuối'),
('Interview Preparation', 'Tài liệu chuẩn bị phỏng vấn kỹ thuật'),
('Problem Solutions', 'Giải pháp cho các bài toán lập trình phổ biến'),
('Framework Guides', 'Hướng dẫn sử dụng các framework và library'),
('Architecture Patterns', 'Các mẫu thiết kế và kiến trúc phần mềm'),
('Performance Optimization', 'Tối ưu hóa hiệu năng ứng dụng'),
('Security Best Practices', 'Các thực hành tốt nhất về bảo mật'),
('Development Tools', 'Hướng dẫn sử dụng các công cụ phát triển');

-- Insert data vào bảng documents (35 tài liệu)
INSERT INTO documents (title, description, content, topic_id, level, duration, students, rating, thumbnail_url, created_by, is_deleted) VALUES
('Thuật toán Sắp xếp cơ bản', 'Tìm hiểu các thuật toán sắp xếp phổ biến như Bubble Sort, Selection Sort, Insertion Sort', 'Tài liệu này sẽ giúp bạn hiểu rõ về các thuật toán sắp xếp cơ bản. Chúng ta sẽ bắt đầu với Bubble Sort - thuật toán đơn giản nhất...', 1, 'Beginner', 45, 234, 4.7, 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=300', 2, FALSE),
('Lập trình OOP với Python', 'Hướng dẫn chi tiết về lập trình hướng đối tượng trong Python', 'Object-Oriented Programming là một paradigm quan trọng trong lập trình. Trong tài liệu này, chúng ta sẽ học về classes, objects, inheritance...', 2, 'Intermediate', 60, 187, 4.8, 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=300', 5, FALSE),
('SQL cơ bản đến nâng cao', 'Từ SELECT cơ bản đến các truy vấn phức tạp với JOIN, subquery', 'SQL là ngôn ngữ truy vấn chuẩn cho cơ sở dữ liệu quan hệ. Tài liệu này bao gồm tất cả từ cú pháp cơ bản đến các kỹ thuật advanced...', 3, 'Intermediate', 90, 156, 4.6, 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=300', 11, FALSE),
('React Hooks Complete Guide', 'Hướng dẫn toàn diện về React Hooks và State Management', 'React Hooks đã thay đổi cách chúng ta viết React components. Tìm hiểu về useState, useEffect, useContext và các custom hooks...', 4, 'Advanced', 75, 298, 4.9, 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=300', 8, FALSE),
('Node.js API Development', 'Xây dựng RESTful API với Node.js và Express', 'Học cách tạo RESTful API mạnh mẽ với Node.js. Từ routing cơ bản đến authentication, middleware và database integration...', 5, 'Intermediate', 80, 145, 4.7, 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=300', 11, FALSE),
('Flutter Widget Deep Dive', 'Tìm hiểu sâu về Flutter Widgets và State Management', 'Flutter widgets là building blocks của mọi ứng dụng Flutter. Tài liệu này sẽ đi sâu vào StatefulWidget, StatelessWidget...', 6, 'Advanced', 65, 123, 4.8, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=300', 8, FALSE),
('Giới thiệu Machine Learning', 'Khái niệm cơ bản và các thuật toán ML phổ biến', 'Machine Learning không còn xa lạ. Tìm hiểu về supervised learning, unsupervised learning và các thuật toán như Linear Regression...', 7, 'Beginner', 55, 276, 4.5, 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=300', 17, FALSE),
('Cybersecurity Fundamentals', 'Nguyên tắc cơ bản về bảo mật thông tin và cyber security', 'Bảo mật là ưu tiên hàng đầu trong phát triển phần mềm. Học về common vulnerabilities, encryption, authentication...', 8, 'Intermediate', 70, 89, 4.6, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=300', 14, FALSE),
('Docker Container Guide', 'Hướng dẫn sử dụng Docker cho beginners và advanced users', 'Containerization đã thay đổi cách deploy ứng dụng. Học Docker từ basic concepts đến production deployment...', 9, 'Intermediate', 50, 167, 4.8, 'https://images.unsplash.com/photo-1667372393086-9d4001d51cf1?w=300', 23, FALSE),
('Unity Game Scripting', 'Lập trình game với Unity và C# scripting', 'Game development với Unity engine. Học về GameObjects, Components, Physics, Animation và game logic programming...', 10, 'Intermediate', 85, 78, 4.4, 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=300', 27, FALSE),
('Blockchain Technology Overview', 'Tổng quan về công nghệ Blockchain và ứng dụng', 'Blockchain không chỉ là Bitcoin. Tìm hiểu về distributed ledger, consensus mechanisms, smart contracts...', 11, 'Beginner', 40, 134, 4.7, 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=300', 29, FALSE),
('Data Analysis with Pandas', 'Phân tích dữ liệu với Python Pandas library', 'Pandas là thư viện mạnh mẽ cho data analysis. Học cách manipulate, clean và analyze data với DataFrames...', 12, 'Intermediate', 60, 198, 4.6, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300', 20, FALSE),
('UI Design Principles', 'Nguyên tắc thiết kế giao diện người dùng hiệu quả', 'Design không chỉ là làm cho đẹp. Học về user psychology, layout principles, color theory, typography...', 13, 'Beginner', 35, 156, 4.5, 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=300', 8, FALSE),
('Microservices Architecture', 'Thiết kế hệ thống với kiến trúc Microservices', 'Microservices là xu hướng architecture hiện tại. Học về service decomposition, API gateway, service discovery...', 14, 'Advanced', 95, 89, 4.9, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=300', 36, FALSE),
('Test Automation Best Practices', 'Các thực hành tốt nhất trong automation testing', 'Testing là part không thể thiếu trong development. Học về unit testing, integration testing, test frameworks...', 15, 'Intermediate', 55, 112, 4.4, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=300', 32, FALSE),
('IoT with Arduino', 'Internet of Things projects với Arduino platform', 'IoT đang everywhere. Học cách build IoT devices với Arduino, sensors, wireless communication...', 16, 'Beginner', 45, 67, 4.3, 'https://images.unsplash.com/photo-1518792528501-352f829886dc?w=300', 21, FALSE),
('Deep Learning Foundations', 'Nền tảng Deep Learning và Neural Networks', 'Deep Learning là subset của Machine Learning. Tìm hiểu về neural networks, backpropagation, CNN, RNN...', 17, 'Advanced', 120, 145, 4.8, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300', 17, FALSE),
('Network Programming in Python', 'Lập trình mạng với Python sockets và protocols', 'Network programming cho phép applications communicate qua network. Học về TCP/UDP, HTTP, websockets...', 18, 'Advanced', 70, 56, 4.5, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=300', 2, FALSE),
('Linux System Administration', 'Quản trị hệ thống Linux cho developers', 'Linux là OS phổ biến nhất cho servers. Học về command line, file systems, processes, permissions...', 19, 'Intermediate', 65, 123, 4.6, 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=300', 23, FALSE),
('Agile Software Development', 'Phương pháp phát triển phần mềm Agile và Scrum', 'Agile đã thay đổi cách teams làm việc. Học về Scrum, Kanban, user stories, sprints, retrospectives...', 20, 'Beginner', 30, 234, 4.2, 'https://images.unsplash.com/photo-1556155092-8707de31f9c4?w=300', 46, FALSE),
('Advanced Python Techniques', 'Các kỹ thuật Python nâng cao cho experienced developers', 'Python có nhiều advanced features. Học về decorators, context managers, metaclasses, async programming...', 2, 'Advanced', 85, 167, 4.7, 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=300', 2, FALSE),
('GraphQL API Design', 'Thiết kế API với GraphQL thay vì REST', 'GraphQL là alternative mạnh mẽ cho REST APIs. Học về queries, mutations, subscriptions, schema design...', 5, 'Advanced', 75, 98, 4.6, 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=300', 5, FALSE),
('MongoDB Database Design', 'Thiết kế database với MongoDB NoSQL', 'NoSQL databases có advantages riêng. Học về document-based storage, indexing, aggregation pipelines...', 3, 'Intermediate', 60, 134, 4.5, 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=300', 11, FALSE),
('React Native Performance', 'Tối ưu hiệu năng ứng dụng React Native', 'Performance là key factor trong mobile apps. Học về optimization techniques, memory management, profiling...', 6, 'Advanced', 55, 78, 4.7, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=300', 8, FALSE),
('Kubernetes Orchestration', 'Container orchestration với Kubernetes', 'Kubernetes là standard cho container orchestration. Học về pods, services, deployments, scaling...', 9, 'Advanced', 90, 89, 4.8, 'https://images.unsplash.com/photo-1667372393086-9d4001d51cf1?w=300', 23, FALSE),
('Computer Vision Basics', 'Giới thiệu Computer Vision và Image Processing', 'Computer Vision là exciting field của AI. Học về image processing, feature detection, object recognition...', 17, 'Intermediate', 70, 112, 4.6, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300', 17, FALSE),
('Cryptography Fundamentals', 'Nền tảng mật mã học trong lập trình', 'Cryptography là core của security. Học về encryption algorithms, hashing, digital signatures, PKI...', 8, 'Advanced', 80, 67, 4.7, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=300', 14, FALSE),
('Git Version Control', 'Quản lý source code với Git và GitHub', 'Git là essential tool cho mọi developer. Học về repositories, branches, merging, conflict resolution...', 20, 'Beginner', 40, 287, 4.4, 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=300', 2, FALSE),
('AWS Cloud Services', 'Các dịch vụ cloud cơ bản trên Amazon Web Services', 'Cloud computing đã become mainstream. Học về EC2, S3, RDS, Lambda và các core AWS services...', 9, 'Intermediate', 85, 156, 4.6, 'https://images.unsplash.com/photo-1667372393086-9d4001d51cf1?w=300', 23, FALSE),
('Redis Caching Strategies', 'Sử dụng Redis cho caching và performance optimization', 'Caching là critical cho performance. Học về Redis data structures, caching patterns, cluster setup...', 3, 'Advanced', 50, 89, 4.5, 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=300', 11, FALSE),
('TypeScript Advanced Types', 'Hệ thống type nâng cao trong TypeScript', 'TypeScript mang static typing đến JavaScript. Học về generics, utility types, conditional types...', 4, 'Advanced', 65, 123, 4.8, 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=300', 2, FALSE),
('Elasticsearch Search Engine', 'Full-text search với Elasticsearch engine', 'Search là feature quan trọng trong applications. Học về indexing, querying, aggregations với Elasticsearch...', 12, 'Advanced', 75, 67, 4.6, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300', 20, FALSE),
('WebSocket Real-time Communication', 'Real-time communication với WebSocket protocol', 'Real-time features đang trở nên phổ biến. Học về WebSocket implementation, socket.io, real-time architectures...', 18, 'Intermediate', 45, 98, 4.5, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=300', 5, FALSE),
('Serverless Architecture', 'Kiến trúc Serverless với AWS Lambda và Functions', 'Serverless là paradigm mới cho cloud applications. Học về Functions as a Service, event-driven architecture...', 9, 'Advanced', 60, 78, 4.7, 'https://images.unsplash.com/photo-1667372393086-9d4001d51cf1?w=300', 23, FALSE),
('Progressive Web Apps', 'Xây dựng Progressive Web Apps với modern standards', 'PWAs combine best của web và mobile apps. Học về service workers, offline functionality, app manifests...', 4, 'Advanced', 70, 134, 4.6, 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=300', 8, FALSE);

-- Insert data vào bảng document_category_links (70 liên kết tài liệu-danh mục)
INSERT INTO document_category_links (document_id, category_id) VALUES
(1, 1), (1, 7), (2, 1), (2, 8), (3, 1), (3, 4), (4, 2), (4, 8), (5, 2), (5, 8),
(6, 2), (6, 8), (7, 1), (7, 7), (8, 1), (8, 11), (9, 2), (9, 12), (10, 2), (10, 8),
(11, 1), (11, 4), (12, 2), (12, 12), (13, 1), (13, 9), (14, 2), (14, 9), (15, 2), (15, 11),
(16, 1), (16, 5), (17, 2), (17, 7), (18, 2), (18, 8), (19, 1), (19, 12), (20, 1), (20, 9),
(21, 2), (21, 8), (22, 2), (22, 4), (23, 2), (23, 4), (24, 2), (24, 10), (25, 2), (25, 12),
(26, 2), (26, 7), (27, 2), (27, 11), (28, 1), (28, 12), (29, 2), (29, 12), (30, 2), (30, 10),
(31, 2), (31, 8), (32, 2), (32, 7), (33, 2), (33, 8), (34, 2), (34, 12), (35, 2), (35, 9);

-- Insert data vào bảng document_modules (105 modules cho 35 tài liệu)
INSERT INTO document_modules (document_id, title, position) VALUES
(1, 'Giới thiệu về Thuật toán Sắp xếp', 1),
(1, 'Bubble Sort Algorithm', 2),
(1, 'Selection Sort Algorithm', 3),
(2, 'OOP Concepts Overview', 1),
(2, 'Classes và Objects', 2),
(2, 'Inheritance và Polymorphism', 3),
(3, 'SQL Fundamentals', 1),
(3, 'Advanced Queries và JOINs', 2),
(3, 'Database Optimization', 3),
(4, 'React Hooks Introduction', 1),
(4, 'useState và useEffect', 2),
(4, 'Custom Hooks Development', 3),
(5, 'Node.js Basics', 1),
(5, 'Express Framework', 2),
(5, 'API Authentication', 3),
(6, 'Flutter Widget Fundamentals', 1),
(6, 'State Management Patterns', 2),
(6, 'Advanced Widget Techniques', 3),
(7, 'Machine Learning Overview', 1),
(7, 'Supervised Learning', 2),
(7, 'Model Evaluation', 3),
(8, 'Security Fundamentals', 1),
(8, 'Common Vulnerabilities', 2),
(8, 'Security Best Practices', 3),
(9, 'Docker Basics', 1),
(9, 'Container Management', 2),
(9, 'Production Deployment', 3),
(10, 'Unity Interface', 1),
(10, 'C# Scripting Basics', 2),
(10, 'Game Logic Implementation', 3),
(11, 'Blockchain Fundamentals', 1),
(11, 'Cryptocurrency Basics', 2),
(11, 'Smart Contract Introduction', 3),
(12, 'Pandas Introduction', 1),
(12, 'Data Manipulation', 2),
(12, 'Data Analysis Techniques', 3),
(13, 'Design Principles', 1),
(13, 'Color và Typography', 2),
(13, 'User Experience Guidelines', 3),
(14, 'Microservices Overview', 1),
(14, 'Service Design Patterns', 2),
(14, 'Communication Strategies', 3),
(15, 'Testing Fundamentals', 1),
(15, 'Automation Frameworks', 2),
(15, 'CI/CD Integration', 3),
(16, 'IoT Concepts', 1),
(16, 'Arduino Programming', 2),
(16, 'Sensor Integration', 3),
(17, 'Neural Networks Basics', 1),
(17, 'Deep Learning Algorithms', 2),
(17, 'Model Training Techniques', 3),
(18, 'Network Programming Basics', 1),
(18, 'Socket Programming', 2),
(18, 'Protocol Implementation', 3),
(19, 'Linux Fundamentals', 1),
(19, 'System Administration', 2),
(19, 'Security và Monitoring', 3),
(20, 'Agile Methodology', 1),
(20, 'Scrum Framework', 2),
(20, 'Team Collaboration', 3),
(21, 'Advanced Python Concepts', 1),
(21, 'Decorators và Metaclasses', 2),
(21, 'Async Programming', 3),
(22, 'GraphQL Fundamentals', 1),
(22, 'Schema Design', 2),
(22, 'Performance Optimization', 3),
(23, 'MongoDB Basics', 1),
(23, 'Document Design', 2),
(23, 'Aggregation Framework', 3),
(24, 'React Native Performance', 1),
(24, 'Memory Management', 2),
(24, 'Optimization Techniques', 3),
(25, 'Kubernetes Architecture', 1),
(25, 'Container Orchestration', 2),
(25, 'Production Deployment', 3),
(26, 'Image Processing Basics', 1),
(26, 'Feature Detection', 2),
(26, 'Object Recognition', 3),
(27, 'Cryptography Principles', 1),
(27, 'Encryption Algorithms', 2),
(27, 'Digital Signatures', 3),
(28, 'Git Fundamentals', 1),
(28, 'Branching Strategies', 2),
(28, 'Collaboration Workflows', 3),
(29, 'AWS Core Services', 1),
(29, 'Cloud Architecture', 2),
(29, 'Cost Optimization', 3),
(30, 'Redis Data Structures', 1),
(30, 'Caching Patterns', 2),
(30, 'Performance Tuning', 3),
(31, 'TypeScript Type System', 1),
(31, 'Advanced Types', 2),
(31, 'Type Safety Patterns', 3),
(32, 'Elasticsearch Setup', 1),
(32, 'Search Queries', 2),
(32, 'Analytics và Aggregations', 3),
(33, 'WebSocket Protocol', 1),
(33, 'Real-time Implementation', 2),
(33, 'Scalability Considerations', 3),
(34, 'Serverless Concepts', 1),
(34, 'Function Development', 2),
(34, 'Event-driven Architecture', 3),
(35, 'PWA Fundamentals', 1),
(35, 'Service Workers', 2),
(35, 'Offline Functionality', 3);

-- Insert data vào bảng document_lessons (210 bài học)
INSERT INTO document_lessons (module_id, title, content, code_example, position) VALUES
(1, 'Tại sao cần thuật toán sắp xếp?', 'Sắp xếp là một trong những operations cơ bản nhất trong computer science...', 'def why_sorting():\n    # Sorting giúp tìm kiếm nhanh hơn\n    return "Better search performance"', 1),
(1, 'Phân loại thuật toán sắp xếp', 'Có nhiều cách phân loại sorting algorithms: stable vs unstable, in-place vs out-of-place...', NULL, 2),
(2, 'Bubble Sort Implementation', 'Bubble Sort so sánh các cặp elements liền kề và swap nếu cần thiết...', 'def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(0, n-i-1):\n            if arr[j] > arr[j+1]:\n                arr[j], arr[j+1] = arr[j+1], arr[j]\n    return arr', 1),
(2, 'Bubble Sort Complexity Analysis', 'Time complexity của Bubble Sort là O(n²) trong worst case...', NULL, 2),
(3, 'Selection Sort Concept', 'Selection Sort tìm minimum element và đưa về đầu array...', 'def selection_sort(arr):\n    for i in range(len(arr)):\n        min_idx = i\n        for j in range(i+1, len(arr)):\n            if arr[min_idx] > arr[j]:\n                min_idx = j\n        arr[i], arr[min_idx] = arr[min_idx], arr[i]\n    return arr', 1),
(4, 'What are Classes?', 'Classes là blueprints để tạo objects. Chúng define attributes và methods...', 'class Student:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    \n    def study(self):\n        return f"{self.name} is studying"', 1),
(4, 'Objects và Instances', 'Objects là instances của classes. Mỗi object có state riêng...', 'student1 = Student("An", 20)\nstudent2 = Student("Bình", 21)\nprint(student1.study())', 2),
(5, 'Inheritance in Python', 'Inheritance cho phép class con inherit attributes và methods từ class cha...', 'class Person:\n    def __init__(self, name):\n        self.name = name\n\nclass Student(Person):\n    def __init__(self, name, student_id):\n        super().__init__(name)\n        self.student_id = student_id', 1),
(7, 'SQL SELECT Statement', 'SELECT là câu lệnh cơ bản nhất để query data từ database...', 'SELECT name, age FROM users\nWHERE age > 18\nORDER BY name;', 1),
(7, 'Filtering với WHERE', 'WHERE clause cho phép filter records dựa trên conditions...', 'SELECT * FROM products\nWHERE price BETWEEN 100 AND 500\nAND category = "Electronics";', 2),
(8, 'INNER JOIN Explained', 'INNER JOIN return records có matching values trong cả hai tables...', 'SELECT u.name, p.title\nFROM users u\nINNER JOIN posts p ON u.id = p.user_id;', 1),
(8, 'LEFT JOIN vs RIGHT JOIN', 'LEFT JOIN return tất cả records từ left table...', 'SELECT u.name, p.title\nFROM users u\nLEFT JOIN posts p ON u.id = p.user_id;', 2),
(10, 'useState Hook Basics', 'useState cho phép add state vào functional components...', 'import React, { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  \n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Count: {count}\n    </button>\n  );\n}', 1),
(10, 'State Updates và Re-rendering', 'Khi state thay đổi, component sẽ re-render với giá trị mới...', 'const [user, setUser] = useState({ name: "", age: 0 });\n\n// Correct way to update object state\nsetUser(prevUser => ({\n  ...prevUser,\n  name: "John"\n}));', 2),
(11, 'useEffect Hook Introduction', 'useEffect cho phép perform side effects trong functional components...', 'import React, { useState, useEffect } from "react";\n\nfunction UserProfile({ userId }) {\n  const [user, setUser] = useState(null);\n  \n  useEffect(() => {\n    fetchUser(userId).then(setUser);\n  }, [userId]);\n  \n  return user ? <div>{user.name}</div> : <div>Loading...</div>;\n}', 1),
(13, 'Express Server Setup', 'Express là minimal web framework cho Node.js...', 'const express = require("express");\nconst app = express();\n\napp.get("/", (req, res) => {\n  res.json({ message: "Hello World" });\n});\n\napp.listen(3000, () => {\n  console.log("Server running on port 3000");\n});', 1),
(13, 'Middleware in Express', 'Middleware functions có access to request và response objects...', 'const logger = (req, res, next) => {\n  console.log(`${req.method} ${req.path}`);\n  next();\n};\n\napp.use(logger);\napp.use(express.json());', 2),
(14, 'JWT Authentication', 'JSON Web Tokens provide secure way to transmit information...', 'const jwt = require("jsonwebtoken");\n\n// Generate token\nconst token = jwt.sign(\n  { userId: user.id }, \n  process.env.JWT_SECRET, \n  { expiresIn: "24h" }\n);\n\n// Verify token\nconst decoded = jwt.verify(token, process.env.JWT_SECRET);', 1),
(16, 'StatefulWidget vs StatelessWidget', 'StatelessWidget không thể thay đổi state sau khi built...', 'class MyStatelessWidget extends StatelessWidget {\n  @override\n  Widget build(BuildContext context) {\n    return Text("Hello Flutter");\n  }\n}\n\nclass MyStatefulWidget extends StatefulWidget {\n  @override\n  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();\n}', 1),
(16, 'setState() Method', 'setState() notify framework rằng internal state đã changed...', 'class _CounterState extends State<Counter> {\n  int _counter = 0;\n  \n  void _incrementCounter() {\n    setState(() {\n      _counter++;\n    });\n  }\n  \n  @override\n  Widget build(BuildContext context) {\n    return Text("Counter: $_counter");\n  }\n}', 2),
(19, 'Linear Regression Basics', 'Linear regression tìm relationship giữa input và output variables...', 'from sklearn.linear_model import LinearRegression\nimport numpy as np\n\n# Training data\nX = np.array([[1], [2], [3], [4], [5]])\ny = np.array([2, 4, 6, 8, 10])\n\n# Create và train model\nmodel = LinearRegression()\nmodel.fit(X, y)\n\n# Make predictions\npredictions = model.predict([[6]])', 1),
(19, 'Model Evaluation Metrics', 'Accuracy, precision, recall là các metrics quan trọng...', 'from sklearn.metrics import accuracy_score, precision_score, recall_score\n\n# Calculate metrics\naccuracy = accuracy_score(y_true, y_pred)\nprecision = precision_score(y_true, y_pred, average="weighted")\nrecall = recall_score(y_true, y_pred, average="weighted")', 2),
(22, 'Common Security Vulnerabilities', 'OWASP Top 10 liệt kê các vulnerabilities phổ biến nhất...', '# SQL Injection Prevention\nimport sqlite3\n\n# WRONG - Vulnerable to SQL injection\nquery = f"SELECT * FROM users WHERE name = \'{user_input}\'"  # DON\'T DO THIS\n\n# CORRECT - Using parameterized queries\ncursor.execute("SELECT * FROM users WHERE name = ?", (user_input,))', 1),
(22, 'Input Validation', 'Validate tất cả user inputs để prevent malicious data...', 'import re\n\ndef validate_email(email):\n    pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"\n    return re.match(pattern, email) is not None\n\ndef sanitize_input(user_input):\n    # Remove potentially dangerous characters\n    return re.sub(r"[<>\"\'%;()&+]", "", user_input)', 2),
(25, 'Docker Images và Containers', 'Images là read-only templates để create containers...', '# Dockerfile example\nFROM python:3.9-slim\n\nWORKDIR /app\n\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\n\nCOPY . .\n\nEXPOSE 8000\n\nCMD ["python", "app.py"]', 1),
(25, 'Docker Compose', 'Docker Compose define và run multi-container applications...', 'version: "3.8"\nservices:\n  web:\n    build: .\n    ports:\n      - "8000:8000"\n    depends_on:\n      - db\n  db:\n    image: postgres:13\n    environment:\n      POSTGRES_DB: myapp\n      POSTGRES_USER: user\n      POSTGRES_PASSWORD: password', 2);

-- Insert data vào bảng document_lesson_completions (150 hoàn thành bài học)
/* INSERT INTO document_lesson_completions (user_id, lesson_id) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5),
(3, 1), (3, 2), (3, 4), (3, 5), (3, 7),
(6, 1), (6, 10), (6, 11), (6, 13), (6, 15),
(7, 2), (7, 3), (7, 7), (7, 8), (7, 10),
(9, 1), (9, 4), (9, 6), (9, 12), (9, 14),
(10, 3), (10, 5), (10, 8), (10, 11), (10, 16),
(12, 1), (12, 2), (12, 9), (12, 13), (12, 17),
(15, 4), (15, 6), (15, 10), (15, 14), (15, 18),
(16, 1), (16, 3), (16, 7), (16, 12), (16, 19),
(18, 2), (18, 5), (18, 9), (18, 15), (18, 20),
(19, 1), (19, 8), (19, 11), (19, 16), (19, 21),
(21, 3), (21, 6), (21, 12), (21, 17), (21, 22),
(22, 1), (22, 4), (22, 9), (22, 18), (22, 23),
(24, 2), (24, 7), (24, 13), (24, 19), (24, 24),
(26, 1), (26, 5), (26, 10), (26, 20), (26, 25),
(28, 3), (28, 8), (28, 14), (28, 21), (28, 26),
(30, 1), (30, 6), (30, 15), (30, 22), (30, 27),
(32, 4), (32, 9), (32, 16), (32, 23), (32, 28),
(34, 1), (34, 2), (34, 17), (34, 24), (34, 29),
(35, 5), (35, 11), (35, 18), (35, 25), (35, 30),
(37, 1), (37, 7), (37, 19), (37, 26), (37, 31),
(38, 3), (38, 12), (38, 20), (38, 27), (38, 32),
(40, 1), (40, 8), (40, 21), (40, 28), (40, 33),
(42, 4), (42, 13), (42, 22), (42, 29), (42, 34),
(44, 1), (44, 9), (44, 23), (44, 30), (44, 35),
(47, 2), (47, 14), (47, 24), (47, 31), (47, 36),
(48, 1), (48, 10), (48, 25), (48, 32), (48, 37),
(50, 6), (50, 15), (50, 26), (50, 33), (50, 38),
(2, 1), (2, 11), (2, 27), (2, 34), (2, 39),
(5, 7), (5, 16), (5, 28), (5, 35), (5, 40); */

-- Insert data vào bảng document_completions (80 hoàn thành tài liệu)
/* INSERT INTO document_completions (user_id, document_id) VALUES */
/* (1, 1), (1, 2), (1, 13), (3, 1), (3, 3),
(6, 7), (6, 12), (7, 4), (7, 5), (9, 11),
(10, 15), (12, 8), (15, 10), (16, 13), (18, 4),
(19, 14), (21, 16), (22, 20), (24, 6), (26, 3),
(28, 13), (30, 20), (32, 15), (34, 1), (35, 25),
(37, 16), (38, 7), (38, 12), (40, 15), (42, 20),
(44, 13), (47, 4), (47, 5), (48, 8), (50, 1),
(2, 21), (2, 28), (5, 22), (5, 29), (8, 24),
(11, 23), (11, 30), (14, 27), (17, 26), (20, 32),
(23, 25), (27, 33), (29, 34), (36, 14), (43, 25),
(46, 20), (49, 35), (1, 28), (3, 21), (6, 31),
(7, 22), (9, 24), (10, 30), (12, 27), (15, 33),
(16, 26), (18, 34), (19, 25), (21, 35), (22, 29),
(24, 31), (26, 23), (28, 32), (30, 28), (32, 34),
(34, 21), (35, 30), (37, 26), (38, 35), (40, 29),
(42, 31), (44, 28), (47, 32), (48, 27), (50, 33); */

-- Insert data vào bảng animations (25 animations)
INSERT INTO animations (document_id, lesson_id, title, type, description, embed_code) VALUES
(1, 1, 'Bubble Sort Visualization', 'sorting', 'Animation cho thấy cách Bubble Sort hoạt động step by step', '<iframe src="/animations/bubble-sort" width="800" height="400"></iframe>'),
(1, 3, 'Selection Sort Animation', 'sorting', 'Visualization của Selection Sort algorithm', '<iframe src="/animations/selection-sort" width="800" height="400"></iframe>'),
(2, 4, 'Class và Object Relationship', 'concept', 'Minh họa mối quan hệ giữa Class và Object trong OOP', '<div class="animation-container" data-type="oop-relationship"></div>'),
(2, 5, 'Inheritance Hierarchy', 'concept', 'Animation shows inheritance hierarchy trong OOP', '<div class="animation-container" data-type="inheritance"></div>'),
(3, 7, 'SQL JOIN Types', 'database', 'Visual representation của các loại JOIN trong SQL', '<iframe src="/animations/sql-joins" width="800" height="500"></iframe>'),
(4, 10, 'React Component Lifecycle', 'framework', 'Animation của React component lifecycle và state changes', '<div class="react-lifecycle-animation" data-hooks="true"></div>'),
(4, 11, 'useEffect Dependencies', 'framework', 'Visualization của useEffect dependency array behavior', '<div class="useeffect-deps-animation"></div>'),
(5, 13, 'HTTP Request Flow', 'network', 'Animation showing HTTP request/response cycle', '<iframe src="/animations/http-flow" width="800" height="400"></iframe>'),
(6, 16, 'Flutter Widget Tree', 'mobile', 'Visualization của Flutter widget tree structure', '<div class="flutter-widget-tree" data-interactive="true"></div>'),
(7, 19, 'Linear Regression Line', 'machine-learning', 'Animation cho thấy linear regression line fitting', '<canvas id="linear-regression-canvas" width="800" height="400"></canvas>'),
(8, 22, 'SQL Injection Attack', 'security', 'Demonstration của SQL injection vulnerability', '<div class="security-demo" data-type="sql-injection"></div>'),
(9, 25, 'Docker Container Lifecycle', 'devops', 'Animation của container creation và management', '<iframe src="/animations/docker-lifecycle" width="800" height="500"></iframe>'),
(10, NULL, 'Unity Physics Simulation', 'game-dev', 'Physics simulation trong Unity game engine', '<canvas id="unity-physics" width="800" height="600"></canvas>'),
(11, NULL, 'Blockchain Transaction', 'blockchain', 'Visualization của blockchain transaction process', '<div class="blockchain-animation" data-blocks="5"></div>'),
(12, NULL, 'Pandas DataFrame Operations', 'data-science', 'Animation của common DataFrame operations', '<div class="pandas-demo" data-interactive="true"></div>'),
(14, NULL, 'Microservices Communication', 'architecture', 'Animation shows service-to-service communication', '<iframe src="/animations/microservices" width="1000" height="600"></iframe>'),
(17, NULL, 'Neural Network Training', 'ai', 'Visualization của neural network training process', '<canvas id="neural-network" width="800" height="600"></canvas>'),
(18, NULL, 'Network Packet Flow', 'networking', 'Animation của network packet routing', '<div class="network-simulation" data-nodes="10"></div>'),
(21, NULL, 'Python Decorator Execution', 'programming', 'Step-by-step decorator execution visualization', '<div class="python-decorator-demo"></div>'),
(22, NULL, 'GraphQL Query Resolution', 'api', 'Animation của GraphQL query resolution process', '<iframe src="/animations/graphql-resolution" width="800" height="500"></iframe>'),
(25, NULL, 'Kubernetes Pod Scaling', 'orchestration', 'Animation của automatic pod scaling', '<div class="k8s-scaling-animation" data-replicas="5"></div>'),
(26, NULL, 'Image Feature Detection', 'computer-vision', 'Real-time feature detection demonstration', '<canvas id="cv-features" width="640" height="480"></canvas>'),
(27, NULL, 'Encryption Algorithm Visualization', 'cryptography', 'Step-by-step encryption process animation', '<div class="encryption-demo" data-algorithm="aes"></div>'),
(29, NULL, 'AWS Service Architecture', 'cloud', 'Interactive AWS services architecture diagram', '<div class="aws-architecture" data-interactive="true"></div>'),
(35, NULL, 'Service Worker Lifecycle', 'pwa', 'PWA service worker installation và activation', '<div class="sw-lifecycle-animation"></div>');
