import { User } from '../models/user.model';

export const mockUsers: User[] = [
  {
    id: 1,
    name: 'Nguyễn Văn An',
    email: 'an.nguyen@example.com',
    avatar_url: '/assets/avatars/user1.png',
    role: 'user',
    is_active: true,
    is_online: true,
    last_seen_at: new Date().toISOString(),
    subscription_status: 'premium',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'Trần Thị Bình',
    email: 'binh.tran@example.com',
    avatar_url: '/assets/avatars/user2.png',
    role: 'user',
    is_active: true,
    is_online: true,
    last_seen_at: new Date().toISOString(),
    subscription_status: 'free',
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 3,
    name: 'Lê Hoàng Cường',
    email: 'cuong.le@example.com',
    avatar_url: '/assets/avatars/user3.png',
    role: 'creator',
    is_active: true,
    is_online: false,
    last_seen_at: '2025-09-11T05:30:00Z',
    subscription_status: 'premium',
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 4,
    name: 'Phạm Minh Đức',
    email: 'duc.pham@example.com',
    avatar_url: '/assets/avatars/user4.png',
    role: 'admin',
    is_active: true,
    is_online: true,
    last_seen_at: new Date().toISOString(),
    subscription_status: 'premium',
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 5,
    name: 'Võ Thị Emy',
    email: 'emy.vo@example.com',
    avatar_url: '/assets/avatars/user5.png',
    role: 'user',
    is_active: true,
    is_online: true,
    last_seen_at: new Date().toISOString(),
    subscription_status: 'free',
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 6,
    name: 'Hoàng Văn Phong',
    email: 'phong.hoang@example.com',
    avatar_url: '/assets/avatars/user6.png',
    role: 'user',
    is_active: true,
    is_online: false,
    last_seen_at: '2025-09-11T04:00:00Z',
    subscription_status: 'premium',
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
  },
  {
    id: 7,
    name: 'Đặng Thị Giang',
    email: 'giang.dang@example.com',
    avatar_url: '/assets/avatars/user7.png',
    role: 'user',
    is_active: true,
    is_online: true,
    last_seen_at: new Date().toISOString(),
    subscription_status: 'free',
    created_at: '2024-01-07T00:00:00Z',
    updated_at: '2024-01-07T00:00:00Z',
  },
  {
    id: 8,
    name: 'Bùi Quang Hải',
    email: 'hai.bui@example.com',
    avatar_url: '/assets/avatars/user8.png',
    role: 'user',
    is_active: true,
    is_online: false,
    last_seen_at: '2025-09-10T22:30:00Z',
    subscription_status: 'premium',
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2024-01-08T00:00:00Z',
  },
];
