version: "3.8"

services:
  api:
    build: .
    container_name: backend_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      API_PREFIX: /api/v1
      CLIENT_URL: http://localhost:4200
      # Database configuration
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: lfysdb
      DB_USER: api_user
      DB_PASSWORD: api_password
      # Judge0 configuration
    volumes:
      - ./uploads:/app/uploads
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - api_network

  mysql:
    image: mariadb:10.4
    container_name: api_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lfysdb
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - api_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: api_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - api_network

volumes:
  mysql_data:

networks:
  api_network:
    driver: bridge
